---
- hosts: all
  remote_user: root
  vars:
    compose_directory: /data/mt-mods-infra
  tasks:
    - name: Checkout git master
      ansible.builtin.git:
        repo: https://github.com/mt-mods/mt-mods-infra
        dest: "{{ compose_directory }}"
        single_branch: yes
        version: master

    - name: Configure services
      community.general.docker_compose:
        project_src: "{{ compose_directory }}"
        pull: yes
        build: yes
        remove_orphans: yes
