[irc]
[irc.libera]
Server="irc.libera.chat:6667"
Nick="MTModsBot"
Password="{{ IRC_LIBERA_PASSWORD }}"
RemoteNickFormat="[{PROTOCOL}] <{NICK}> "

[discord]
[discord.mtmods]
Token="{{ DISCORD_MTMODS_TOKEN }}"
Server="905447873402003486"
RemoteNickFormat="[{PROTOCOL}] <{NICK}> "

[matrix]
[matrix.mtmods]
Server="https://matrix.org"
Login="@mtmods:matrix.org"
Password="{{ MATRIX_MTMODS_PASSWORD }}"
RemoteNickFormat="[{PROTOCOL}] <{NICK}> "
NoHomeServerSuffix=true
#HTMLDisable=true

[[gateway]]
name="maingateway"
enable=true

[[gateway.inout]]
account="irc.libera"
channel="#mt-mods"

[[gateway.inout]]
account = "discord.mtmods"
channel="🛰modding"

[[gateway.inout]]
account = "matrix.mtmods"
channel="!IuYhGtsAusgKYlpUCs:matrix.org"

[[gateway]]
name="offtopicgateway"
enable=true

[[gateway.inout]]
account="irc.libera"
channel="#mt-mods-offtopic"

[[gateway.inout]]
account = "discord.mtmods"
channel="🏛lounge"

[[gateway.inout]]
account = "matrix.mtmods"
channel="!dQppybfdWYiNSoXjYP:matrix.org"
